-- Seed de 80 perguntas para o Teste das Cores (5 Dinâmicas Humanas)
INSERT INTO color_questions (question_number, prompt, option_azul, option_rosa, option_amarelo, option_verde, option_branco, active)
VALUES
(1,'Quando você recebe um novo projeto, sua primeira reação costuma ser:','Analisar objetivos, riscos e impactos de longo prazo antes de agir','Pensar rapidamente em novas ideias e possibilidades futuras','Conversar com as pessoas envolvidas para alinhar expectativas','Buscar experiências passadas e entender todo o contexto','Entender claramente o propósito e estruturar um plano prático',true),
(2,'Em reuniões longas, você se sente mais confortável quando:','A pauta é lógica, objetiva e bem estruturada','Há troca intensa de ideias e debate','Existe espaço para diálogo e conexão entre as pessoas','O contexto completo é apresentado com calma','O objetivo e os próximos passos estão claros',true),
(3,'Sob pressão de prazo, você tende a:','Eliminar distrações e manter foco total','Acelerar decisões para manter o movimento','Apoiar o time emocionalmente','Manter um ritmo constante sem precipitação','Reorganizar o plano para ganhar eficiência',true),
(4,'Ao aprender algo novo, você prefere:','Leitura estruturada e lógica','Experimentar ideias e testar hipóteses','Aprender conversando com outras pessoas','Assimilar aos poucos conectando experiências','Aprender fazendo, com aplicação prática',true),
(5,'O que mais te incomoda no trabalho?','Falta de foco e superficialidade','Ritmo lento e excesso de repetição','Clima frio ou distante','Mudanças bruscas sem contexto','Desorganização e falta de método',true),
(6,'Quando precisa tomar uma decisão importante, você:','Avalia dados e impactos futuros','Decide rapidamente com base no potencial','Considera como as pessoas serão afetadas','Reflete com calma integrando vários fatores','Define critérios e escolhe a opção mais eficiente',true),
(7,'Em trabalhos em grupo, você geralmente assume o papel de:','Estratégia e análise','Impulso inicial e ideias','Facilitação e conexão','Integração e estabilidade','Organização e execução',true),
(8,'Seu ritmo ideal de trabalho é:','Sequencial e focado','Rápido e dinâmico','Flexível e relacional','Constante e orgânico','Estruturado e produtivo',true),
(9,'Quando surge um conflito, você tende a:','Analisar os fatos de forma objetiva','Ver como oportunidade de mudança','Promover diálogo e reconciliação','Evitar rupturas e preservar relações','Resolver de forma prática',true),
(10,'Você se sente mais motivado quando:','O trabalho tem coerência e significado','Há desafios e novidades','O ambiente é acolhedor','Existe estabilidade','Os resultados são concretos',true),
(11,'Ao explicar algo complexo, você prefere:','Organizar do geral para o específico','Usar exemplos provocativos','Criar conexão com quem ouve','Contar a história completa','Mostrar como funciona na prática',true),
(12,'Mudanças frequentes no trabalho:','Precisam ser bem justificadas','São estimulantes','Devem considerar o impacto emocional','Devem acontecer gradualmente','Devem melhorar a eficiência',true),
(13,'Você se sente mais produtivo quando:','Pode trabalhar sozinho e concentrado','Pode alternar ideias e tarefas','Trabalha em equipe','Tem tempo suficiente','Tem processos claros',true),
(14,'Em projetos longos, você se destaca por:','Manter consistência conceitual','Manter energia e movimento','Manter engajamento do time','Manter continuidade','Garantir execução até o fim',true),
(15,'O que mais gera estresse para você?','Falta de clareza','Burocracia e lentidão','Ambiente tenso','Pressa excessiva','Improviso',true),
(16,'Quando recebe feedback, você prefere que seja:','Objetivo e direto','Inspirador','Empático','Contextualizado','Orientado à ação',true),
(17,'Você costuma planejar pensando mais em:','Longo prazo','Possibilidades futuras','Pessoas envolvidas','Continuidade','Execução',true),
(18,'Em apresentações, você prefere:','Slides claros','Debates','Interação','Explicações detalhadas','Demonstrações práticas',true),
(19,'Seu maior ponto forte é:','Clareza mental','Criatividade','Empatia','Estabilidade','Organização',true),
(20,'Você se sente desconfortável quando:','Há superficialidade','Tudo é previsível','Não há troca humana','Não há tempo','Não há método',true),
(21,'Ao iniciar algo novo, você busca primeiro:','Compreensão conceitual','Ideias inovadoras','Alinhamento com pessoas','Histórico e contexto','Estrutura prática',true),
(22,'Quando alguém discorda de você, você tende a:','Argumentar com lógica','Debater ideias','Escutar sentimentos','Refletir antes de responder','Buscar uma solução objetiva',true),
(23,'Em ambientes caóticos, você reage melhor quando pode:','Organizar mentalmente','Criar alternativas','Apoiar pessoas','Manter estabilidade','Impor ordem',true),
(24,'Para você, liderança é principalmente:','Visão e princípios','Movimento e inovação','Cuidado com pessoas','Continuidade','Direção clara',true),
(25,'Ao lidar com erros, você prefere:','Analisar causas','Aprender rápido e seguir','Acolher o impacto emocional','Corrigir com calma','Ajustar processos',true),
(26,'Você prefere tarefas que exigem:','Concentração','Criatividade','Interação','Paciência','Execução',true),
(27,'Quando algo dá errado, sua reação inicial é:','Entender o porquê','Buscar nova alternativa','Apoiar envolvidos','Esperar estabilizar','Corrigir imediatamente',true),
(28,'Você se sente mais confortável trabalhando:','Sozinho','Em grupos dinâmicos','Em times próximos','Em ambientes previsíveis','Com papéis claros',true),
(29,'Seu estilo de comunicação é mais:','Objetivo','Entusiasmado','Expressivo','Calmo','Direto',true),
(30,'Você prefere ambientes que valorizam:','Raciocínio','Inovação','Relacionamento','História','Resultados',true),
(31,'Quando precisa convencer alguém, você usa mais:','Argumentos lógicos','Visão de futuro','Conexão emocional','Contexto','Praticidade',true),
(32,'Você se frustra mais quando:','Faltam dados','Nada muda','As pessoas estão distantes','Tudo é apressado','Nada anda',true),
(33,'Seu foco natural está em:','Pensamento','Ideias','Pessoas','Processos orgânicos','Sistemas',true),
(34,'Você aprende melhor quando:','Lê e analisa','Experimenta','Conversa','Observa com tempo','Aplica',true),
(35,'Para você, sucesso significa:','Coerência','Evolução','Harmonia','Continuidade','Eficiência',true),
(36,'Você prefere lideranças que sejam:','Racionais','Inspiradoras','Humanas','Estáveis','Organizadas',true),
(37,'Quando recebe uma tarefa vaga, você:','Pede clareza conceitual','Propõe caminhos','Pergunta quem está envolvido','Busca histórico','Cria estrutura',true),
(38,'Você se sente mais seguro quando:','Tudo faz sentido','Há possibilidades','Há apoio humano','Nada é apressado','Tudo está planejado',true),
(39,'Você tende a evitar ambientes:','Confusos','Monótonos','Friamente técnicos','Instáveis','Desorganizados',true),
(40,'Ao finalizar um projeto, você valoriza mais:','Aprendizado','Inovação','Relacionamentos','Continuidade','Entrega',true),
(41,'Você prefere trabalhar com líderes que:','Pensam estrategicamente','Estimulem ideias','Se importem com pessoas','Respeitem o ritmo','Definam bem processos',true),
(42,'Quando algo muda de última hora, você:','Questiona a lógica','Se adapta rápido','Verifica impacto emocional','Precisa de tempo','Reorganiza tudo',true),
(43,'Você lida melhor com pressão quando:','Pode se concentrar','Pode agir rápido','Pode conversar','Pode manter ritmo','Pode planejar',true),
(44,'Seu maior medo profissional é:','Perder coerência','Ficar estagnado','Quebrar relações','Ser atropelado','Falhar na execução',true),
(45,'Você prefere decisões que sejam:','Bem fundamentadas','Ágeis','Humanizadas','Cuidadosas','Eficientes',true),
(46,'Você se sente mais reconhecido quando:','Valorizam seu pensamento','Valorizam suas ideias','Valorizam sua empatia','Valorizam sua constância','Valorizam sua entrega',true),
(47,'Para você, comunicação eficaz é:','Clara','Inspiradora','Conectada','Contextual','Objetiva',true),
(48,'Você se sente melhor trabalhando em ambientes:','Silenciosos','Dinâmicos','Colaborativos','Tranquilos','Organizados',true),
(49,'Você tende a confiar mais em:','Dados','Intuição criativa','Pessoas','Experiência','Processos',true),
(50,'Você prefere tarefas que tenham:','Lógica','Liberdade','Interação','Tempo','Objetivo claro',true),
(51,'Quando algo é urgente, você:','Avalia riscos','Age rápido','Chama pessoas','Mantém calma','Executa',true),
(52,'Você se sente mais confortável quando:','Há coerência','Há novidade','Há proximidade','Há previsibilidade','Há estrutura',true),
(53,'Você prefere receber instruções:','Bem explicadas','Flexíveis','Conversadas','Detalhadas','Diretas',true),
(54,'Você se destaca mais em atividades que exigem:','Análise','Criação','Relacionamento','Persistência','Organização',true),
(55,'Você evita decisões quando:','Faltam dados','Nada inspira','Há conflito emocional','Tudo está confuso','Não há plano',true),
(56,'Você prefere resolver problemas:','Pensando','Testando','Conversando','Observando','Executando',true),
(57,'Você se sente mais cansado quando:','Há ruído','Nada muda','O clima pesa','Tudo acelera','Tudo improvisa',true),
(58,'Você valoriza mais colegas que são:','Coerentes','Inovadores','Empáticos','Confiáveis','Produtivos',true),
(59,'Você prefere ambientes onde:','Pensar é valorizado','Criar é incentivado','Conectar é essencial','Respeitar ritmo é regra','Entregar é prioridade',true),
(60,'Você tende a medir sucesso por:','Qualidade do raciocínio','Impacto das ideias','Qualidade das relações','Sustentação no tempo','Resultados alcançados',true),
(61,'Ao iniciar o dia, você prefere:','Planejar mentalmente','Visualizar possibilidades','Conversar','Entrar no ritmo','Organizar tarefas',true),
(62,'Você se frustra quando líderes:','Não explicam','Não inovam','Não escutam','Aceleram demais','Não organizam',true),
(63,'Você aprende mais com:','Leitura','Experimentação','Troca','Vivência','Prática',true),
(64,'Você prefere desafios que sejam:','Intelectuais','Criativos','Humanos','Progressivos','Operacionais',true),
(65,'Você tende a confiar mais quando:','Tudo é lógico','Há entusiasmo','Há empatia','Há consistência','Há método',true),
(66,'Você prefere projetos que:','Façam sentido','Inovem','Unam pessoas','Se sustentem','Entreguem valor',true),
(67,'Você se sente mais confortável quando decisões são:','Bem analisadas','Rápidas','Compartilhadas','Cuidadosas','Executáveis',true),
(68,'Você reage melhor a mudanças quando:','Entende o racional','Vê oportunidade','Sente apoio','Tem tempo','Vê ganho prático',true),
(69,'Você prefere ambientes que:','Estimulem pensamento','Estimulem criação','Estimulem relação','Estimulem estabilidade','Estimulem produtividade',true),
(70,'Você se destaca mais quando pode:','Pensar profundamente','Criar caminhos','Apoiar pessoas','Manter constância','Executar com eficiência',true),
(71,'Você se sente desmotivado quando:','Nada faz sentido','Tudo é repetitivo','O clima é frio','Tudo muda rápido','Nada é organizado',true),
(72,'Você prefere decisões baseadas em:','Análise','Intuição criativa','Sensibilidade','Experiência','Planejamento',true),
(73,'Você se sente mais seguro quando:','Há clareza conceitual','Há inovação','Há conexão','Há previsibilidade','Há estrutura',true),
(74,'Você tende a se destacar em times que:','Pensam estrategicamente','Criam soluções','Valorizam pessoas','Mantêm ritmo','Executam bem',true),
(75,'Você prefere resolver conflitos por meio de:','Análise','Mudança','Diálogo','Tempo','Ação',true),
(76,'Você se sente mais confortável com líderes que:','Explicam o porquê','Inspiram','Acolhem','Respeitam ritmo','Organizam',true),
(77,'Você prefere ambientes onde:','Pensar é prioridade','Criar é regra','Relacionar é essencial','Continuar é valorizado','Entregar é foco',true),
(78,'Você mede bons resultados por:','Coerência','Impacto','Relacionamento','Sustentação','Eficiência',true),
(79,'Você se sente mais produtivo quando:','Pode se concentrar','Pode inovar','Pode interagir','Pode manter ritmo','Pode executar',true),
(80,'Você prefere trabalhos que:','Exijam reflexão','Estimulem ideias','Conectem pessoas','Respeitem o tempo','Tenham propósito claro',true)
ON CONFLICT (question_number) DO UPDATE
SET prompt = EXCLUDED.prompt,
	option_azul = EXCLUDED.option_azul,
	option_rosa = EXCLUDED.option_rosa,
	option_amarelo = EXCLUDED.option_amarelo,
	option_verde = EXCLUDED.option_verde,
	option_branco = EXCLUDED.option_branco,
	active = EXCLUDED.active,
	updated_at = NOW();
